### ISSUE TITLE
Question about design choice and it's impact on screenplay/solid?

### ISSUE THREAD

**Issue by bandophahita** [perrygoy/screenpy#14]
First I will preface I'm still learning to incorporate the SOLID principles and just started utilizing the screenplay pattern.  So what I'm about to ask might require a little hand holding to guide me in the right direction.

I noticed that neither the `Wait` class nor the `BrowseTheWeb.to_wait_for` method return the `WebElement` (if found).  My first reaction was "well that would have been useful" but then I wondered if there was a deliberate design choice behind it.

Prior to screenplay pattern, I would often have used the `WebElement` returned by `WebDriverWait` after it had been found.
Using screenpy, if I want to wait for a new page load I have to wait for the `WebElement` and then do another locate to interact with it.  Perhaps not the most expensive set of actions, but feels a little redundant?  

Am I overthinking things?  Or would it make sense for `BrowseTheWeb.to_wait_for` and `Wait` to return the elements?  Would this violate one of the solid principles?

**Comment by perrygoy** [comment]
Hey @bandophahita! Great question, and i'm glad you asked it.

I'll start with laying out my intentions for the action and ability you mentioned, just to let you know where i was coming from when i made them. That might, in itself, answer your question, but i'll say more words after that about `Performable` and why the actions in ScreenPy behave the way they do.

When i created ScreenPy, i figured typically users would be using `BrowseTheWeb.to_wait_for` through `Wait`, not directly. Some folks might need to if they're creating custom actions that need to wait for something in a slightly different way, but `Wait` was my imagined entrypoint. Using Actions is done through the `Actor.attempts_to` or `Actor.was_able_to` methods. For example:

```python3
Perry = AnActor.named("Perry").who_can(BrowseTheWeb.using_firefox())

Perry.attempts_to(
    Open.their_browser_on(LOGIN_URL),
    Wait.for_the(LOGIN_BUTTON),
    Click.on_the(LOGIN_BUTTON),
)
```

That does mean that we will be asking Selenium for the element twice, once in the `Wait` and once in `Click`. In my experience, this is not a problem, but i do understand how it can seem inefficient.

However, i do suppose it is a little bit limiting for me to have even `BrowseTheWeb.to_wait_for` not return the element, since `WebDriverWait` itself does. I have a feeling you may have known all of the above, and are writing an action that needs to wait and then act on the same element. Or, if you aren't, someone might be, and is frustrated by this same situation.

I'm working on another (small) update, i can easily update `BrowseTheWeb.to_wait_for` to return the WebElement, if the wait's condition is satisfied. 

How do you feel about that?

**Comment by bandophahita** [comment]
I think that would be a welcome addition to the library. 

That said I'm happy to see I'm on the right path with learning to adapt to new design principles.  I started to realize, after I asked my question, that all I would need to do would be to extend BrowseTheWeb and could solve the problem on my end without a lot of work, thus being a good reminder of the open/closed principle.

Another option I considered was creating common tasks combining actions like `WaitAndClick`; which didn't feel like it would violate single responsibility since the the latter action is often dependent on the results of the first.

Thank you for taking the time to translate and build this library.  You've helped me get very excited about adopting the screenplay pattern; so much so, I've been brainstorming either a companion package or a pull request with additional actions or abilities like LocalStorage handling and clearing cache/cookies.

**Comment by perrygoy** [comment]
You are certainly on the right path, absolutely! 

> Thank you for taking the time to translate and build this library. You've helped me get very excited about adopting the screenplay pattern; so much so, I've been brainstorming either a companion package or a pull request with additional actions or abilities like LocalStorage handling and clearing cache/cookies.

This comment makes me very happy, i'm glad this library has provided such inspiration to you. PRs are welcome, and those sound like things that would be helpful!

I'll leave this issue open until i've finished, pushed up, and released the impending update, so you can be notified when the `BrowseTheWeb.to_wait_for` update has been put in.

**Comment by perrygoy** [comment]
Woops, i think some automation closed this. It's not quite ready to be closed yet. I might be completely removing `BrowseTheWeb.to_wait_for` and the other prescribed methods like `.to_find`. Stay tuned~!

**Comment by perrygoy** [comment]
OK, and now, i've pushed `3.0.0`. Your question actually sparked quite a bit of figurative soul-searching.

Shortly after i pushed the update to the `to_wait_for` method of `BrowseTheWeb`, i was struck with a sudden realization that this method was a problem. (By the way, it's currently 3am my time, so i'm sorry if this message waxes a little poetic.) When you asked your question, this ability was:
* Handling the browser instance.
* Providing a middleware-ish API to Selenium's webdriver.
* ... OK i think there were only two things it was doing.

Still—`BrowseTheWeb` was doing too many things, violating the S in SOLID! So i ripped out `to_wait_for`. Then i ripped out `to_find` as well, because why was that any different? These small deletions caused a **big** unclenching in the code, and it feels so nice—there was an annoying circular import between `BrowseTheWeb` and `Target` that is gone now; `BrowseTheWeb` feels much sleeker, and `Wait` can do magic.

(Hm... i think *technically* `BrowseTheWeb` should have only the `.using` method and i should strip out the `.using_X` convenience methods as well... 🤔)

Anyway, it was actually your question that gave me this strike of inspiration. You had me re-examining code that i hadn't really touched in ... at least a year. Maybe longer. Code i hadn't re-evaluated since i wrote it almost four years ago, before it even lived in this repository. So thank you for your question! You helped improved ScreenPy. :)

To answer your specific situation, though—to write your new action, you will be directly using the actor's `BrowseTheWeb` ability to pluck out the `browser` from it, and using `WebDriverWait` directly in the action. You can take a look at the [new `Wait` code](https://github.com/perrygoy/screenpy/blob/trunk/screenpy/actions/wait.py#L95) to see how it does it.

I've bloviated long enough—let me know if you have further questions, or if you strongly object to this change! I'll leave this issue open for you to close, so you can signify your satisfaction (if you feel thusly sated, at least).

**Comment by bandophahita** [comment]
Thus far I think the changes are great. I saw the changes to Wait logging and think it was the better choice even if the natural language reading of the log is a little awkward.  

Old
```
17:54:39  INFO Billy waits for the password Field to be clickable...
17:54:40  INFO Billy waits for the username Field to be clickable...
17:54:40  INFO Billy waits for the forgotpass Button to be clickable...
```
vs new
```
15:45:28  INFO Billy waits using element_to_be_clickable with [password Field]...
15:45:28  INFO Billy waits using element_to_be_clickable with [username Field]...
15:45:28  INFO Billy waits using element_to_be_clickable with [forgotpass Button]...
```

As far as my original question goes; **would it be awkward if `Wait.perform_as` returned the output from `WebDriverWait`**?
As I've gotten used the screenplay pattern I am not seeing a cleanway of getting that element back after the `perform_as` is called, not unless `attempts_to` was able to return the output as well.   I don't know how it could since we can pass in multiple actions into it.
```
element = actor.attempts_to(Wait(self._timeout).seconds_for(target).using(condition))
```
Or if we deliberately broke the pattern like so:
```
element = Wait(self._timeout).seconds_for(target).using(condition).perform_as(actor)
```
Functionally ok, but feels dirty and reads worse.

I keep having this nagging notion that there is a solution where `Wait` (or some other implementation of it) could return the element but doesn't break the screenplay pattern.  I can't picture it yet, but perhaps something like another abstraction wait is passed into which handles the element.

**Comment by bandophahita** [comment]
It occurs to me that `Target` isn't one of the Protocols.  Should it be?  `found_by` works just like `answered_by` with a natural language alternative name for the method.  At that point does it have special properties that would not qualify it as a Question?

The above got me thinking about the screenplay diagram and how actions and questions work.  
![image](https://user-images.githubusercontent.com/4211287/108434339-1f49be80-720d-11eb-9dbc-fa260575d934.png)

The part that confuses me is; we **USE** selenium to ask questions and yet the diagram suggests we should only be USING selenium via the actions granted by the ability.  Using selenium constitutes as an action.  
In a way, the diagram doesn't seem to make sense.  How can I question the system unders test without using the ability which granted to me by selenium?

Is the difference between actions vs questions similar to 'look but don't touch'?  If the ability is some sort of observation it can be qualified as a question but if it causes any sort of state change it's considered an action?

**Comment by perrygoy** [comment]
> the natural language reading of the log is a little awkward.

Yeah, i agree, and actually put back the nice logging after seeing my own reports. It did mean that i had to switch from `Wait.for_the(TARGET)` to `Wait.for_the(TARGET).to_appear()`, but i think that makes the test more readable anyway. Grab that 3.0.1 update and enjoy the better logs, too!

As far as your thoughts about `Wait.perform_as` returning the element—returning anything but `None` will violate the `Performable` protocol. Granted, i *made* that protocol, so i can define it to be whatever it needs to be, but i think that allowing things to be returned from it would encourage writing things like your example. Plus your thoughts about how `Actor.attempts_to` would need to figure out how to pass all that back are right on the money. 

I think you're making a new action, right? I don't think there's anything wrong with you using the actor's ability directly to create a `WebDriverWait` in that new action, like `Wait` does. Maybe you could even inherit from `Wait` to get all its other functionality, then overwrite the `perform_as` method to use the element returned by `WebDriverWait`. Would that work for what you're doing?

> It occurs to me that Target isn't one of the Protocols. Should it be? 

Boy howdy, maybe. I have plans to add support for [Appium](https://appium.io/) someday, which would need to have special targets for the mobile elements. So far there's just the one though, and i repeat the YAGNI mantra constantly while i code...

>  `found_by` works just like `answered_by`

You spun my head right round with this comment, but i think Target still needs to be separate. It is special because it enables a lot of other things, and is different from, say, `Element` because it needs to be able to fail in a way that `Element` doesn't. But this was a really cool observation you had! It made me go check the code side-by-side to make sure i couldn't just replace one of them.

The diagram question is a good one. I'm wondering what's up with the lack of connection between abilities and questions. For ScreenPy, at least, there would be an arrow connecting those two. Looking at SerenityBDD's implementation of the [Text question](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-screenplay-webdriver/src/main/java/net/serenitybdd/screenplay/questions/Text.java), it looks like they also leverage the actor's `BrowseTheWeb` ability through their implementation of `Target.resolveAllFor`. It's strange that the chart doesn't reflect that. (P.S. SerenityBDD is the library that inspired me to create something similar for Python!)

> Is the difference between actions vs questions similar to 'look but don't touch'?

I'm comfortable with that definition—actions are touches, questions are looks. An actor answers a question by observing the state of the page (through their ability) and finding a specific piece of information, while an actor performs an action by, well, acting upon some part of the page (through their ability). 

Phew, sorry for the wall. Does all this help clear it up some?

**Comment by bandophahita** [comment]
> Does all this help clear it up some?
It absolutely does.  I appreciate the discussion and your thoughtfulness. It would seem that you geek out on this as much as I do.  

I have a couple of hacks that I would like to eventually submit for review and potential Pull Request.  I feel like asking different questions in this thread would risk going off topic. Does it make sense to open a new question thread?

**Comment by perrygoy** [comment]
> Does it make sense to open new question threads for each?

It might! That would keep the discussion focused for sure.

I've been wondering if i should open up some sort of Slack or Discord or IRC channel for ScreenPy discussion. I'm just not sure if many people would find that useful.
