### ISSUE TITLE
Brainstorm question about browser synchronization

### ISSUE THREAD

**Issue by bandophahita** [perrygoy/screenpy#18]
I've been pondering the idea of including browser synchronization into actions.   Consider the following.
```
actor.attempts_to(Open.their_browser_on(URL))
actor.should_see_the(
        (Text.of_the(WELCOME_MESSAGE),
         ContainsTheText("Welcome! Please Login to your account"))
        )
```
From an automation standpoint this test can be problematic because there is no synchronization happening.  If the site is faster than the test it'll pass.  On the other hand if the site is slower than the test for some reason (loading, stress, etc)  selenium can raise NoSuchElementException.  The folks at selenium of course gave us `WebDriverWait` to combat this. ScreenPy utilizes it in the `Wait` action.

In theory, we would just need to include a `Wait` immediately after the `Open`
```
actor.attempts_to(Open.their_browser_on(URL),
                  Wait.for_(WELCOME_MESSAGE))
actor.should_see_the(
    (Text.of_the(WELCOME_MESSAGE),
     ContainsTheText("Welcome! Please Login to your account")))
```
Hold on a sec, `Wait` allows me to add the condition to look for.  Which is just like what the test is looking for.
```
actor.attempts_to(
    Open.their_browser_on(URL),
    Wait.for_(WELCOME_MESSAGE).to_contain_text(
        "Welcome! Please Login to your account"))
actor.should_see_the(
    (Text.of_the(WELCOME_MESSAGE),
     ContainsTheText("Welcome! Please Login to your account")))
```
At this point the test is redundant from the wait. 

This got me wondering if there was a way to add the option to synchronize in the screenplay?
Since `Text` calls on `Target.found_by` to do the actual looking, what if there was a way to have target decide what method to use when looking for the element: `find_element` vs `wait.until`?

I haven't figured out what it would look like, but maybe something along these lines...
```
actor.attempts_to(Open.their_browser_on(URL))
actor.should_see_the(
    (Text.of_the(WELCOME_MESSAGE.via_synchronization()),
     ContainsTheText("Welcome! Please Login to your account")))
```

The one problem I can see with the approach is how does the author control the setup of WebDriverWait (e.g. timeout) and how do they include the condition while still maintaining screenplay readability?
```
actor.attempts_to(Open.their_browser_on(URL))
actor.should_see_the(
    (Text.of_the(WELCOME_MESSAGE.sync_until_visible()),
     ContainsTheText("Welcome! Please Login to your account")))
```

Does this idea have merit?

**Comment by perrygoy** [comment]
It sounds like you're looking for the [Implicit Wait](https://screenpy-docs.readthedocs.io/en/latest/topics/waiting.html#implicit-waits) strategy, which can be done by using the `implicitly_wait` method on the webdriver before passing it in.

In my opinion, explicit waits are a better option because implicit waits can mask problems with your site (like some elements loading quickly but others taking longer to appear), and because "Explicit is better than implicit." (_The Zen of Python_, by Tim Peters). 

But! Like you said, it can drastically cut down on the number of `Wait`s you'll need in your code. I think it's mostly up to the suite author which approach they prefer. 

As to the other part of your question, about the `Wait` condition managing to make your assertion step superfluous, i've actually removed some assertion steps in my own tests by favoring using a wait strategy. I've been calling them "soft assertions," along with things like how the test expects to arrive at a certain page after a link/button is clicked.

**Comment by perrygoy** [comment]
Hey @bandophahita, i was just poking around GitHub and noticed they actually have a "Discussions" page that i can opt-in to. I've enabled [Discussions](https://github.com/perrygoy/screenpy/discussions) for ScreenPy now, so let's move there!
