### ISSUE TITLE
Cannot use `MakeNote` and `noted_under` in the same Actions list

### ISSUE THREAD

**Issue by pgoy-dod** [perrygoy/screenpy#51]
Say we have this:

```python
the_actor.attempts_to(
    MakeNote.of_the(Text.of_the(EXAMPLE_FIELD)).as_("notable note"),
    Enter.the_text(noted_under("notable note")).into_the(EXAMPLE_INPUT),
)
```

We get a `KeyError` from that because the Director's notebook is empty. The `MakeNote` action hasn't been performed yet!!

How to solve this quandary? Is there some soup of dunder-methods available that can delay actually getting the value from the Director's notebook until the Action's `perform_as` asks for it? Figure it out!

**P.S.:** There is a workaround, but i hate it:

```python
the_actor.attempts_to(
    MakeNote.of_the(Text.of_the(EXAMPLE_FIELD)).as_("notable note")
)
# just split them up 
the_actor.attempts_to(
    Enter.the_text(noted_under("notable note")).into_the(EXAMPLE_INPUT),
)

**Comment by bandophahita** [comment]
It occurs to me that `MakeNote` is performable -- thus requiring the actor to be passed into the action -- whereas `noted_under` isn't performable.  It feels weird to me that they aren't both actions or aren't both (whatever `note_under` is classified as).

**Comment by bandophahita** [comment]
Looking at `MakeNote`, I think SRP is the problem.  Answering a question vs noting the answer to that question (in hindsight) would qualify as two different responsibilities.  Though, I'm not exactly sure how to unmarry them and still have things work from a natural language standpoint.  

I didn't say anything before because I thought it was an unqualified opinion, but I think this just outlined why I wasn't keen on `MakeNote`.  I feel like the responsibility for tracking variables lies at the level of the test; even if that means breaking the natural language flow.

I would like to be wrong because I love the idea of having screenplay pattern through the entirety of a test.

**Comment by pgoy-dod** [comment]
> whatever `noted_under` is classified as

Yeah, it's kind of a new thing. I called them `directions` because they're things that use the `Director`. I kind of imagined the `Director` issuing them, even though it's technically the other way around.

> Looking at `MakeNote`, I think SRP is the problem.

I think you're right that it might be a slight breakage. `MakeNote` needs to know how to get the answer from the question, and also needs to pass the answer along to the `Director`. But i think if i just say "`MakeNote` is responsible for giving an answered question to the `Director`," maybe that still fits?? :P

What i think needs to happen is `noted_under` needs to do something special where it is also deferred until later, somehow. I really don't know for sure how i'm going to do this.

**Comment by perrygoy** [comment]
This might just be an honest limitation here.

I looked through all the dunders, none would work. I considered returning a lambda and figuring out how to tell everything it needed to call it, yuck. I even dove into `ctypes` to see if i could return a pointer to the memory location that `notebook["notable note"]` lives at so Python would just look there, maybe? I think i've gone too far down.

**Comment by WandyYing** [comment]
I think the root of the problem is that resolutions needs to be answered. Why don't you add methods (like `answered_by`) to resolutions. What do you think?@perrygoy @bandophahita

**Comment by bandophahita** [comment]
If the director is the one to do the actual note taking it feels odd to have `MakeNote` be a performable action by the actor.
I don't know what to do about this yet... but it's this thought that keeps nagging me.

**Comment by perrygoy** [comment]
> Why don't you add methods (like answered_by) to resolutions. What do you think?

I've thought about this, but there aren't any Resolutions that actually need the actor. Resolutions just handle the comparison between what they are given and what value they were instantiated with.

> `TakeNotes` as an ability... `Note` as a resolution

This was actually how this whole feature started out! But i ran into some problems with it. It seemed like `TakeNotes` ought to be an intrinsic Ability of Actors, which was a big question mark. If `Noted` is a Resolution, then it can't be used anywhere else except assertions. Without passing the Actor in to `Note`, it can't get at the Actor's `TakeNotes` Ability, which caused that whole mess. There's also the whole "natural language" part of it...

... suffice to say, i don't think the Ability/Resolution route will work.

> it feels odd to have MakeNote be a performable action by the actor.

I hear this one, yeah. It feels like the most expected thing, though, to me. The `Director` is hidden completely from the flow, so unless you go digging you don't know who is actually holding the note. But it does seem a little strange. Think of it like a really haughty Actor telling the Director to take a note. :P

There is *something* about all this that feels off, though. Maybe i could make a class instead of a function and overwrite all of the comparison/indexing/etc. methods to use the Director's noted key...?

**Comment by WandyYing** [comment]
> There is _something_ about all this that feels off, though. Maybe i could make a class instead of a function and overwrite all of the comparison/indexing/etc. methods to use the Director's noted key...?

First of all, let's forget the director.

My idea is that as an actor, he should have the ability(`TakeNotes`) to remember things. As an actor, he should be able to answer questions. As an actor, he should be able to answer(`Note`) what he remembers(`MakeNote`).  So, there is no director to record what actors need to remember. It's the actor who answers what he's seen.


In my plan, there is a big change, which is for resolutions. The new resolutions will be similar to question, which can accept `Question` or `string`. At the same time, actors need to add `.answer` method to answer questions.

**Comment by pgoy-dod** [comment]
That does sound like some big changes, @WandyYing. You're free to submit a PR with those changes implemented, but i did already give the `TakeNotes` ability route a go, and we didn't really like the result. I'm interested if your approach will be able to solve the problems i ran into.

**Comment by perrygoy** [comment]
As for my attempts, i did something very _quesitonable_ and even that still didn't work. It was an `Imposter` class that overwrote every one of the [Data Model](https://docs.python.org/3/reference/datamodel.html dunder methods) to relay them to the Director's note instead, so we could pass the `Imposter` in instead. Which *almost* worked! 

... If the Action does anything to the accepted input, it breaks. Like how `Enter` tries to provide nicer strings for Selenium's `Keys`. *Sigh*.

So i think this is just a legit limitation of the implementation. I have exhausted every idea i can think of.

**Comment by WandyYing** [comment]
> Those do sound like some big changes, @WandyYing. You're free to submit a PR with those changes implemented, but i did already give the `TakeNotes` ability route a go, and we didn't really like the result. I'm interested if your approach will be able to solve the problems i ran into!
Let me have a try. :)


> On the flipside, @WandyYing, you suggested catching the `KeyError` on the PR, and now i agree! We should put some sort of explanation for users who fall into this trap. :(
Thanks @perrygoy

**Comment by bandophahita** [comment]
> First of all, let's forget the director.

I'm in agreement with this.  

@WandyYing I'll be interested in what you come up with as well.

**Comment by WandyYing** [comment]
:(  I've made some attempts, and there are still some bugs and incomplete tests. In addition, when designing the test, I found that we may use the notebook in the following scenarios.

```python
def test_basic_auth2(Perry: Actor) -> None:
    """Basic authentication is accepted by the basic auth endpoint."""
    test_username = "USER"
    test_password = "PASS"

    when(Perry).attempts_to(
           TakeNote.of_the(test_username).as_("notable_note"),

           SendGETRequest.to(f"{BASIC_AUTH_URL}/{noted_under('notable_note')}/{test_password}").with_(
            auth=(test_username, test_password)
        ),
    )
```
`noted_under` may exist in a string:(. so it's not going to get `actor`. But I didn't come up with a good solution. ha...  I found that `director` or global parameter  may be essential.
I'll keep trying. But don't expect too much.


BTW, I fixed this issue using director first, another method implements a singleton. #52

**Comment by perrygoy** [comment]
Thanks for the attempts, @WandyYing! It sounds like you ran into the same problems i did. 

For what it's worth, i've actually been enjoying the `Director` in my test suite. We've found several places where we've been able to use note-taking to slim down our tests or make them more straightforward. I personally find it to be really nice for readability. That's just my opinion, though.

I left a comment on your PR! Thanks for submitting one! I think i just need some more information about your change.

**Comment by perrygoy** [comment]
As mentioned in the above commit, i'm admitting defeat. There's now a section in the docs which documents the issue, the workaround, and references this ticket, and a new error message which links to that section.

We put in a good try, team. Thanks for all the discussion and thoughts and attempts!

@WandyYing and @bandophahita, i know both of you don't really like the `Director` approach. If inspiration comes to either or both of you in a flash, i am (as always) open to PRs!

**Comment by bandophahita** [comment]
I think it is more accurate to say I don't think the Director should be used to perform actions which the actor should be doing.  I think the idea of a Director as an entity has merit.

It's possible I'm being overly pedantic about it; the verbs used when reading that an actor is "taking notes" reads as if the _actor_ is storing that variable when in truth the director is the one keeping track of things.

I think when it comes to an actor storing variables they ought to be in the scope of the actor, because.... that's just proper?  I'm having a hard time articulating why that "feels" right.

**Comment by perrygoy** [comment]
Ah ha, i understand. And i do agree, it does feel a little backwards. 

I wonder, would changing the action name to `TellDirectorToTakeANote` make it feel better?

**Comment by bandophahita** [comment]
As I have been reading through the serenity-bdd repo I saw their implementation of being able to save variables.  In their version the Actor has three methods `remember`,`recall`, `forget`.   It's basically the same thing as what the director does with storing the data in a dictionary.  

They then have a class `Remembered` which serves to access those methods on the actor while keeping screenplay readability.  I'm curious if we shouldn't have that as well?

**Comment by perrygoy** [comment]
> In their version the Actor has three methods `remember`, `recall`, forget`.

I had tried this approach but felt like it gave the actor too much responsibility. That led to trying to do it though an ability, my thoughts about innate abilities, and that whole rabbit hole. The reason that we couldn't really do it through an Action is because of how i wanted it to be available everywhere—as a value passed in to another Action, as an expected value for a Resolution, able to be used in Tasks, or even useable in between `was_able_to`/`attempts_to`/`should` blocks. 

While (technically) an Action could still do all those things, it just felt clunky when i tried it out:

```python
the_actor.should(
    See.the(Text.of_the(WELCOME_BANNER), ReadsExactly(TheRemembered("welcome message").perform_as(the_actor)))
)
```
